use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# AppWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :main_website, MainWebsite.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "jd-website.gigalixirapp.com", port: 4000],
  check_origin: [
    "jd-website.gigalixirapp.com"
  ],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

config :main_website,
  css_link_tag: ~s(<link rel="stylesheet" href="/css/app.css" media="screen,projection" />),
  js_script_tag: ~s(<script src="/js/app.js"></script>),
  proxy_base_url: "${PROXY_BASE_URL}",
  proxy_secret: "${PROXY_SECRET}",
  static_path: ""

# Do not print debug messages in production
config :logger, level: :info

config :actionkit,
  base: "${AK_BASE}",
  username: "${AK_USERNAME}",
  password: "${AK_PASSWORD}"
